# PYTHON REFRESHERS ASSIGNMENT

###### 1. Write functions, along with proper code documentation and formatting:

In [2]:
# given number
number = 67

# prime number is always greater than 1
if number > 1:
    for i in range(2, number):
        if (number % i) == 0:
            print(number, "is not a prime number")
            break
    else:
        print(number, "is a prime number")

# if the entered number is less than or equal to 1
# then it is not prime number
else:
    print(number, "is not a prime number")

67 is a prime number


b.To find the longest word in a sentence given as input by the user

In [29]:
# To find the Longest word

# Reading sentence from user

sentence = input("Enter sentence: ")

# Finding longest word
longest = max(sentence.split(), key=len)

# Displaying longest word
print("Longest word is: ", longest)

Enter sentence: the greatest of all
Longest word is:  greatest


c. To find how many times a given user-inputted substring is repeated in another user inputted string

In [1]:
# defining a function that will take two argument
def count_substring(string, sub_string):
    inc = 0
    for i in range(0, len(string)): # giving range and finding length of the given string
        slice_object = slice(i,len(sub_string)+i)
        count = len(string[slice_object]) # finding the length of the slice_object
        if(count == len(sub_string)):
            if(sub_string == string[slice_object]):
                inc = inc + 1
    return inc

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()

    count = count_substring(string, sub_string)
    print(count)

one plus one minus one is one
one
4


###### 2. Create the following class with the given attributes and methods;

a. Standard -
* Attributes: Std name, No of enrolled students, Overall GPA
* Methods: getStd, getEnrolled, getOGPA

In [35]:
# Standard class
class standard:
    def __init__(self,std_name,no_of_enrolled_students,OGPA):
        self.std_name = std_name
        self.no_of_enrolled_students = no_of_enrolled_students
        self.OGPA = OGPA
        
    def getStd(self):  # defining getStd method
        return self.std_name
    
    def getEnrolled(self): # defining getEnrolled method
        return self.no_of_enrolled_students
    
    def getOGPA(self):  # defining getOGPA method
        return  self.OGPA    
obj = standard("nikhil", 5, 7)    

In [36]:
obj.getStd()

'nikhil'

In [37]:
obj.getEnrolled()

5

In [38]:
obj.getOGPA()

7

b. Students class with Standard as its super class  - 
* Attributes: Name,Roll No., Standard, Math marks, English Marks, Science Marks, Social Marks
* Methods: getName, getRollNo, getStd, getGPA

In [42]:
#Students class with Standard as its super class 
class Students(standard):
    def __init__(self,Name,Roll_No,Standard_name,Math_marks,English_marks,Science_marks,Social_marks): # defining constructor
            self.Name = Name
            self.Roll_No = Roll_No
            self.Standard_name = Standard_name
            self.Math_marks = Math_marks
            self.English_marks = English_marks
            self.Science_marks = Science_marks
            self.Social_marks = Social_marks
            
    def getName(self):
        return self.Name
    def getRollNo(self):
        return self.Roll_No
    def getStd(self):
        return self.Standard_name
    def getGPA(self):
        avg_marks = (self.Math_marks+self.English_marks+self.Science_marks+self.Social_marks)/4
        gpa = avg_marks/9
        return round(gpa,2)
obj1 = Students ('nikhil', 2, '5th', 45, 50, 43, 53)    

In [44]:
obj1.getName()

'nikhil'

In [45]:
obj1.getRollNo()

2

In [46]:
obj1.getStd()

'5th'

In [47]:
obj1.getGPA()

5.31

c. Explanation:
* getName, getRollNo, getStd methods should give the name, roll number and standard of the student. 
* getGPA should give the average marks of math,english, science and social marks scaled to 10-points. Same applies for all the attributes and methods in the Standard superclass.

In [49]:
 # Creating objects for each class
 # creating object for Standard class first
std1 = standard('10th standard', 90,8.4 )
std2 = standard('9th standard', 80,7.4 )

# creating object for Students class
student1 = Students('akhil','55','10th standard',56,80,89,68)
student2 = Students('manoj','50','9th standard',80,36,75,65)

print("Name : ",student1.getName())
print("Roll No : ",student1.getRollNo())
print("Standard : ",student1.getStd())
print("GPA : ",student1.getGPA())

Name :  akhil
Roll No :  55
Standard :  10th standard
GPA :  8.14


###### 3. Answer the following:

a. Create a function to find the indices of a parameter passed to the function in a user inputted array. Ex: f(0,[1,2,0,0,4]) gives [2,3] as output


In [28]:
# importing numpy library
import numpy as np
# defining function
def function(no,arr):
    out=[]
    n=0
    # giving range
    for i in arr:
        if i==no:
            out.append(n)
        n+=1
    return out
print(function(0,[1,2,0,0,4]))
    

[2, 3]


b. Create a random vector of size 30 and find the mean value

In [40]:
# printing 30 random values
n = np.random.random(30)
print(n)
print("mean of the vector")
# and printing mean of those 30 random values
np.mean(n)

[0.24391661 0.48812346 0.03255006 0.25340098 0.78184205 0.3923596
 0.30711378 0.74721198 0.25685238 0.26745051 0.57905437 0.9540328
 0.40487015 0.04135424 0.90868159 0.35468456 0.5854454  0.52564005
 0.85444307 0.64892695 0.27960931 0.07984737 0.87149304 0.35426921
 0.11570997 0.74068031 0.16763201 0.45043737 0.22472575 0.95513241]
mean of the vector


0.46224971119623465

c. Create a 2d array with 1 on its edges and 0 in all other indices

In [15]:
# importing numpy library
import numpy as np
# giving the structure for 1's
x = np.ones((5,5))
# printing 1 on the borders and 0's inside the array
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


d. Write a Numpy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [19]:
# giving the structure for 1's
x = np.ones((3,3))
print("Checkerboard pattern:")
# printing the checkboard pattern 
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
